<Project>
  <PropertyGroup>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
    <Authors>Dean Edis</Authors>
    <Company>Dean Edis (DeanTheCoder)</Company>
    <Copyright>Copyright (c) 2026 Dean Edis</Copyright>
  </PropertyGroup>
</Project>

