<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>MechRewired.Core</AssemblyName>
    <RootNamespace>MechRewired</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../DTC.Core/DTC.Core/DTC.Core.csproj" />
  </ItemGroup>
</Project>
