<Project Sdk="Godot.NET.Sdk/4.7.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AssemblyName>MechRewired</AssemblyName>
    <RootNamespace>MechRewired</RootNamespace>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MechRewired.Core/MechRewired.Core.csproj" />
    <PackageReference Include="SmackerSharp" Version="1.0.0" />
    <PackageReference Include="StbImageSharp" Version="2.30.16" />
  </ItemGroup>
</Project>
